export const midpointEscrowAbi = [
  {
    type: "function",
    name: "nextProjectId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "projects",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "client", type: "address" },
      { name: "freelancer", type: "address" },
      { name: "token", type: "address" },
      { name: "totalAmount", type: "uint256" },
      { name: "remainingAmount", type: "uint256" },
      { name: "reviewDeadline", type: "uint256" },
      { name: "disputeStartTime", type: "uint256" },
      { name: "burnedIntervals", type: "uint32" },
      { name: "status", type: "uint8" },
      { name: "exists", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "submissionCids",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "projectDescriptions",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "previewDecayBurn",
    stateMutability: "view",
    inputs: [{ name: "projectId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "createProjectNative",
    stateMutability: "payable",
    inputs: [{ name: "freelancer", type: "address" }],
    outputs: [{ name: "projectId", type: "uint256" }],
  },
  {
    type: "function",
    name: "createProjectNative",
    stateMutability: "payable",
    inputs: [
      { name: "freelancer", type: "address" },
      { name: "description", type: "string" },
    ],
    outputs: [{ name: "projectId", type: "uint256" }],
  },
  {
    type: "function",
    name: "createProjectERC20",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "freelancer", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "projectId", type: "uint256" }],
  },
  {
    type: "function",
    name: "createProjectERC20",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "freelancer", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "description", type: "string" },
    ],
    outputs: [{ name: "projectId", type: "uint256" }],
  },
  {
    type: "function",
    name: "submitWork",
    stateMutability: "nonpayable",
    inputs: [
      { name: "projectId", type: "uint256" },
      { name: "ipfsCid", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "approveSubmission",
    stateMutability: "nonpayable",
    inputs: [{ name: "projectId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimTimeoutPayment",
    stateMutability: "nonpayable",
    inputs: [{ name: "projectId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "dispute",
    stateMutability: "nonpayable",
    inputs: [{ name: "projectId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "applyDecayBurn",
    stateMutability: "nonpayable",
    inputs: [{ name: "projectId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "mutualSettlement",
    stateMutability: "nonpayable",
    inputs: [
      { name: "projectId", type: "uint256" },
      { name: "freelancerCutBps", type: "uint256" },
    ],
    outputs: [],
  },
] as const;
